- hosts: all
  become: true
  user: vagrant 
  tasks:
    - name: Déploiement site web
      git:
        repo: https://github.com/cloudacademy/static-website-example.git
        dest: /var/www/html/website
