- hosts: all
  become: true
  user: vagrant 
  tasks:

    - name: install apache2 pour debian
      package:
        name: "{{ webserver }}"
      #when: ansible_os_family == 'Debian' 

    #- name: install httpd pour centos
      #package:
       # name: "{{ webserver }}"
      #when: ansible_os_family == 'RedHat'

    - name: Installer quelques dépendances 
      package:
        name: 
          - git
