- hosts: all
  become: true
  user: vagrant 
  tasks:

    - name: install apache2 pour debian
      package:
        name: apache2
      when: ansible_os_family == 'Debian' 

    - name: install httpd pour centos
      package:
        name: httpd
      when: ansible_os_family == 'RedHat'

    - name: Installer quelques dépendances 
      package:
        name: 
          - git
