- hosts: all
  become: true
  user: vagrant 
  tasks:
    - name: Démarrage du service
      service:
        name: "{{ webserver }}"
        state: started
        enabled: true
      when: ansible_os_family == 'Debian'

    - name: Démarrage du service
      service:
        name: "{{ webserver }}"
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'
